# To run the production build:
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build

version: '3.8'

services:
  # Name of the service within docker compose
  # This service contains a dist of common TS types and Zod schemas, for sharing
  # between backend and frontend
  common:
    # Build context
    build:
      # Location from which the Dockerfile is executed
      context: ./common
      # Location of the Dockerfile
      dockerfile: Dockerfile
      # Stage in the dockerfile to build
      target: builder
    volumes:
      # Volume to store the built files for sharing with other services
      - common_dist:/app/dist

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      NODE_ENV: development
    volumes:
      - ./backend:/app
      - /app/node_modules
      - common_dist:/app/common/dist
    depends_on:
      - common
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: development
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - common_dist:/app/common/dist
    depends_on:
      - backend
      - common

volumes:
  common_dist:
  postgres_data: