# To run the production build:
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build

version: '3.8'

services:
  # Name of the service within docker compose
  # This service contains a dist of common TS types and Zod schemas, for sharing
  # between backend and frontend
  common:
    # Build context
    build:
      # Location from which the Dockerfile is executed
      context: .
      # Location of the Dockerfile
      dockerfile: common/Dockerfile
      # Stage in the dockerfile to build
      target: builder
    volumes:
      # Make common_dist available to other services
      - common_dist:/app/dist
      - common_node_modules:/app/node_modules

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: production
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      NODE_ENV: production
    volumes:
      - common_dist:/app/common/dist
      - frontend_dist:/app/frontend/dist
      - /app/common/node_modules
      - /app/node_modules
    depends_on:
      - common
      - db
      - frontend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: production
    ports:
      - "4173:4173"
    volumes:
      - /app/common/node_modules
      - /app/node_modules
      - common_dist:/app/common/dist
      - frontend_dist:/app/dist
    depends_on:
      - common

volumes:
  common_dist:
  common_node_modules:
  frontend_dist:
  postgres_data: